### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/hbridge#2]
(Taken from a text file stored locally).

- [ ] add error handling
- [x] add logging
- [ ] consider styling the file choosing button
- [ ] make sure file choosing button has text on mobile (not just a small square)
- [ ] Stop saying "Click a file name to download." when there are not files. Instead say to upload files.
- [x] Consider renaming as Hbridge.
- [ ] Fix problem where running with nodemon loses text on each upload
- [ ] Smarter upload sorting
- [ ] Copy text buttons
- [ ] Delete buttons?
- [x] Show IP and port the server is running on 

Some may already be complete.
